name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  gh-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo "Hello"
  gh-actions-2:
    runs-on: ubuntu-latest
    steps: 
      - name: get repository code
        uses: actions/checkout@v3
      - name: install
        run: sudo apt update && upgrade -y


