name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  gh-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo "Hello"
      - name: print user name
        run: echo "$USER"
             echo "$PWD"

